spring:
  config:
    import: aws-parameterstore:/config/ch4-aws/prod/
  cloud:
    aws:
      region:
        static: ${AWS_REGION:ap-northeast-2}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

logging:
  level:
    root: info
